### ISSUE TITLE
module not defined

### ISSUE THREAD

**Issue by mxmtsk** [corbanbrook/dsp.js#25]
After the latest comit I get an "uncaught referenceerror: module is not defined" when running in the browser. how can I fix it?

**Comment by timqian** [comment]
same problem for me, example `fft.html` not working in my browser

Firefox 46.0.1
Chrome 50

**Comment by juanto121** [comment]
@mxmtsk b4dc02e was added to support the library as an npm package, commenting out this section [dsp.js/L2303-L2322](https://github.com/corbanbrook/dsp.js/blob/52d60e4ece9158b2dac9261790d45421a1556cae/dsp.js#L2303-L2322) should allow you to use the library in the browser. Or maybe use browserify but I'm not sure.

@timqian the examples use MozAudioAvailable which according to [this](https://developer.mozilla.org/en-US/docs/Archive/Mozilla/Introducing_the_Audio_API_Extension#The_MozAudioAvailable_event) is an absolete API. You could make the fft.html example work by using the [WebAudioAPI](https://developer.mozilla.org/es/docs/Web_Audio_API). And also, the audio files are missing but you can find them [here](https://github.com/DamonOehlman/tile5-site/tree/master/audio)

**Comment by mxmtsk** [comment]
@juanto121 Okay, I get it but we load the packages via bower and merge & minify all our dependencies via grunt. It's pretty bad practice to edit vendor files I guess. Every developer that joins our project and loads the dependencies will start with getting this error... there **must** be a different solution. Checking if module itself is defined could be a solution, I'll try it out and make a pull request if it works

**Comment by Paul-C-F** [comment]
@juanto121 @timqian I started migrating this library from dsp.js to WebAudioAPI, haven't finished it yet but here's more or less what changes (modified from the squarewave sample, may vary depending on the sample you're testing):

`// Setup experimental audio out
      //var output = new Audio();

      //if ( typeof output.mozSetup === 'function' ) {
      //  output.mozSetup(1, sampleRate, 1);
      // }

      //Get audio context and setup buffer
      var audioCtx = new AudioContext();
      var buffArray = audioCtx.createBuffer(1, bufferSize, sampleRate);
      var buff = buffArray.getChannelData(0);

      var audioWriter = function(s) {     
        //output.mozWriteAudio(s);
        //Fill Buffer
        for (i = 0; i < 8192; ++i)
        {
          buff[i] = s[i];
        }

        //Setup an AudioNode to play the buffer
        var source = audioCtx.createBufferSource();
        source.buffer = buffArray;
        source.connect(audioCtx.destination);
        source.start();
      }`

**Comment by tlrobinson** [comment]
#22 broke loading dsp.js in browsers (unless you use a module bundler like webpack/browserify). Line 2303 should be something like `if (typeof module !== 'undefined' && module && module.exports) {` instead.

cc @alexcastillo

**Comment by alexcastillo** [comment]
Sorry about that guys!

I opened a PR with the fix.

cc @tlrobinson @mxmtsk
